//
//  PDFExporter.swift
//  FlowLedger
//
//  Created by Ehtisham Khalid on 08.11.2025.
//

import UIKit

enum PDFExporter {
    struct ReportBlock {
        let title: String
        let lines: [String]
    }

    /// Generates a very simple A4 PDF with blocks of text. Returns a file URL in the temp directory.
    static func makePDFFile(fileName: String, title: String, blocks: [ReportBlock]) throws -> URL {
        let pageRect = CGRect(x: 0, y: 0, width: 595, height: 842) // A4 @ 72dpi
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        let url = FileManager.default.temporaryDirectory.appendingPathComponent("\(fileName).pdf")
        try? FileManager.default.removeItem(at: url)

        try renderer.writePDF(to: url) { ctx in
            ctx.beginPage()

            let margin: CGFloat = 36
            var cursor = CGPoint(x: margin, y: margin)

            func draw(_ string: String, font: UIFont, color: UIColor = .label) {
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color
                ]
                let size = (string as NSString).size(withAttributes: attrs)
                (string as NSString).draw(at: cursor, withAttributes: attrs)
                cursor.y += size.height + 6
            }

            // Header
            draw(title, font: .boldSystemFont(ofSize: 20))
            cursor.y += 6

            // Blocks
            for block in blocks {
                draw(block.title, font: .boldSystemFont(ofSize: 15))
                for line in block.lines {
                    draw("• \(line)", font: .systemFont(ofSize: 12), color: .secondaryLabel)
                }
                cursor.y += 12
                if cursor.y > pageRect.height - 80 {
                    ctx.beginPage()
                    cursor = CGPoint(x: margin, y: margin)
                }
            }

            // Footer
            cursor.y = pageRect.height - margin - 12
            draw("Generated by FlowLedger", font: .systemFont(ofSize: 10), color: .tertiaryLabel)
        }

        return url
    }
}
